#Workflow rescrito para utilizar workflow reutilizável
#         uses: PajmaB/php-workflows/.github/workflows/login.yml@master

name: CI via Workflow Reutilizável

on:
  push:
    branches: [ master ]
  pull_request: